"""Recovery-aware Markdown trace projection.

Round 2 review #5 required a human-readable ``trace.md``
projection with two subsections:

    1. Recovery Cycle — per-step recovery outcomes
    2. Branch Lineage — fork graph + ancestry

Commit G.2 implements :class:`TraceMarkdownProjection` which
renders the two subsections from the trace events + branch
registry. The output is plain Markdown; downstream tooling
(CI dashboards, change reviewers) can render it.

Boundary:

    * Reads :class:`TraceEvent` + :class:`BranchRegistry`.
    * Writes ``trace.md`` via :func:`write_projection`.
    * Does **not** call :class:`TraceStore.append_dict`.
    * Does **not** call :class:`RecoveryExecutor`.
"""

from __future__ import annotations

from dataclasses import dataclass
import html
from typing import Iterable

from agent.execution.branch_ancestry import BranchRegistry
from agent.execution.branch_events import (
    EVENT_TYPE_BRANCH_CREATED,
    EVENT_TYPE_REPLAN_CREATED,
)
from agent.trace.markdown_escape import escape_markdown
from agent.trace.recovery_projections import (
    ProjectionProtocol,
    ProjectionResult,
)
from agent.execution.recovery_events import (
    EVENT_TYPE_RECOVERY_REQUESTED,
    EVENT_TYPE_RECOVERY_RESULT,
)
from agent.trace.events import EventType, TraceEvent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _event_payload_str(payload: object) -> str:
    """Render a payload as ``key=value`` pairs joined by ``; ``.

    Accepts any object — ``Mapping`` for normal events, ``None``
    for placeholder events. Non-mapping payloads fall back to
    ``str(payload)``.
    """
    def safe(value: object) -> str:
        escaped = escape_markdown(html.escape(str(value), quote=True))
        return escaped.replace("[", "\\[").replace("]", "\\]")

    if hasattr(payload, "items"):
        return "; ".join(
            f"{safe(k)}={safe(v)}"
            for k, v in payload.items()  # type: ignore[attr-defined]
        )
    return safe(payload)


# ---------------------------------------------------------------------------
# TraceMarkdownProjection
# ---------------------------------------------------------------------------


class TraceMarkdownProjection:
    """Render a ``trace.md`` with two subsections.

    The two subsections are:

    1. **Recovery Cycle** — for each step with recovery events,
       render a table of ``recovery_requested`` /
       ``recovery_result`` / ``replan_created``.
    2. **Branch Lineage** — render the branch tree using the
       :class:`BranchRegistry`, plus a per-branch list of
       recovery events.

    If the trace has no recovery events, the Recovery Cycle
    subsection is empty ("No recovery cycles recorded.").
    If the registry is empty, the Branch Lineage subsection
    is empty ("No branches recorded.").
    """

    name: str = "trace_md"

    def project(
        self,
        events: list[TraceEvent],
        *,
        branch_registry: BranchRegistry,
    ) -> ProjectionResult:
        md_lines: list[str] = []
        md_lines.append("# Trace")
        md_lines.append("")
        md_lines.append(
            "Auto-generated by P2.2 Commit G.2 — "
            "do not edit by hand."
        )
        md_lines.append("")
        md_lines.append("## Recovery Cycle")
        md_lines.append("")
        md_lines.extend(self._render_recovery_cycle(events))
        md_lines.append("")
        md_lines.append("## Branch Lineage")
        md_lines.append("")
        md_lines.extend(self._render_branch_lineage(events, branch_registry))
        md_lines.append("")

        payload = {
            "schema": "trace.md/v1",
            "content": "\n".join(md_lines),
        }
        return ProjectionResult(name=self.name, payload=payload)

    # -----------------------------------------------------------------
    # Recovery Cycle subsection
    # -----------------------------------------------------------------

    def _render_recovery_cycle(
        self,
        events: Iterable[TraceEvent],
    ) -> list[str]:
        recovery_events = [
            e for e in events
            if e.event_type in (
                EventType.RECOVERY_REQUESTED,
                EventType.RECOVERY_RESULT,
                EventType.REPLAN_CREATED,
            )
        ]
        if not recovery_events:
            return ["No recovery cycles recorded."]

        # Group by step_id, preserve first-seen order.
        by_step: dict[str, list[TraceEvent]] = {}
        order: list[str] = []
        for event in recovery_events:
            sid = event.step_id or "unknown"
            if sid not in by_step:
                order.append(sid)
                by_step[sid] = []
            by_step[sid].append(event)

        lines: list[str] = []
        for sid in order:
            lines.append(f"### Step `{sid}`")
            lines.append("")
            lines.append(
                "| event_type | branch_id | payload |"
            )
            lines.append(
                "| --- | --- | --- |"
            )
            for event in by_step[sid]:
                payload_str = _event_payload_str(event.payload)
                lines.append(
                    f"| `{event.event_type.value}` "
                    f"| `{event.branch_id}` "
                    f"| `{payload_str}` |"
                )
            lines.append("")
        return lines

    # -----------------------------------------------------------------
    # Branch Lineage subsection
    # -----------------------------------------------------------------

    def _render_branch_lineage(
        self,
        events: Iterable[TraceEvent],
        registry: BranchRegistry,
    ) -> list[str]:
        if not registry._branches:  # type: ignore[attr-defined]
            return ["No branches recorded."]

        # Find root branches (parent_branch_id is None).
        roots = [
            b for b in registry._branches.values()  # type: ignore[attr-defined]
            if b.parent_branch_id is None
        ]
        if not roots:
            return ["No root branches recorded."]

        # Index branch_created events by branch_id for the per-branch
        # event list.
        branch_events: dict[str, list[TraceEvent]] = {}
        for event in events:
            if event.event_type is EventType.BRANCH_CREATED:
                bid = event.payload.get("branch_id")
                if isinstance(bid, str):
                    branch_events.setdefault(bid, []).append(event)

        lines: list[str] = []
        for root in roots:
            lines.extend(self._render_branch_tree(root, registry, branch_events))
        return lines

    def _render_branch_tree(
        self,
        branch,
        registry: BranchRegistry,
        branch_events: dict[str, list[TraceEvent]],
        depth: int = 0,
    ) -> list[str]:
        lines: list[str] = []
        indent = "  " * depth
        marker = "└─ " if depth > 0 else ""
        fork = branch.forked_from_checkpoint_id or "(no checkpoint)"
        parent = branch.parent_branch_id or "(root)"
        lines.append(
            f"{indent}{marker}**{branch.branch_id}** "
            f"(forked from `{fork}`, parent `{parent}`)"
        )
        # Per-branch event list.
        if branch.branch_id in branch_events:
            for event in branch_events[branch.branch_id]:
                lines.append(
                    f"{indent}    - `{event.event_type.value}`: "
                    f"{_event_payload_str(event.payload)}"
                )
        # Children.
        for child_id in registry.children(branch.branch_id):
            try:
                child = registry.get(child_id)
            except KeyError:
                continue
            lines.extend(
                self._render_branch_tree(child, registry, branch_events, depth + 1)
            )
        return lines


__all__ = ["TraceMarkdownProjection"]
